### ISSUE TITLE
Вебинар 

### ISSUE THREAD

**Issue by djvang** [djvang/spalah-app#10]
http://prntscr.com/km03s8 - нужно чтобы максимально помещалось в экран ... можно задать min-height: 100vh и минимальный padding

**Comment by djvang** [comment]
http://prntscr.com/km04ln - межстрочный и отступы проверить

**Comment by djvang** [comment]
http://prntscr.com/km05ja - в любом случае делаем min-height: 100vh и navbar

**Comment by kathie04** [comment]
Done
