### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by djvang** [djvang/spalah-app#7]
http://i.prntscr.com/kwB3PNueQ4_spfUBL3n_KA.png  - желательно использовать navbar но для этой страницы можно сделать модификацию. Так как если захотят встать туда навигацию будет мысль что нужно нужно было использовать уже готовый navbar

**Comment by djvang** [comment]
Также кнопка закрытия должны быть ссылкой и иконка должна быть в material-icon или font-awesome

**Comment by kathie04** [comment]
Done
