### ISSUE TITLE
Checkbox и Radio

### ISSUE THREAD

**Issue by djvang** [djvang/spalah-app#9]
http://prntscr.com/km025y - не нужно чтобы обтекал чекбокс или радиобаттон. Для этого можно задать класс на обертку .checkbox или .radio и через него сделать стили

**Comment by djvang** [comment]
http://prntscr.com/km03a7 - нету стилей?

**Comment by kathie04** [comment]
http://prntscr.com/km03a7 - нету стилей?  - есть стили на состояние checked
